=== katucker/esfapr/aprMap.schema.json
{
    "$schema":"https://json-schema.org/draft/2020-12/schema",
    "$id":"https://data.ed.gov/schemas/aprMap.schema.json",
    "title":"Annual Performance Report Map",
    "description":"Specifies parameters for extracting data values from a workbook of consolidated Annual Performance Report responses and constructing HTML files, each containing the text of a corresponding approved Information Collection Instrument and the data values provided in a given response.",
    "type": "object",
    "properties": {
        "subfund": {
            "title": "Subfund",
            "description": "The abbreviation of the subfund corresponding to the data values reported.",
            "enum": [
                "EANS",
                "ESF-Gov",
                "ESF-SEA",
                "ESSER",
                "GEER",
                "HEER"
            ]
        },
        "reporting_year": {
            "title": "Reporting year",
            "description": "The performance year for which the data values were reported.",
            "type":"string"
        },
        "datafile_pattern":{
            "title": "Datafile pattern",
            "description": "Filename glob pattern for the datafile containing the values to use for constructing Annual Performance Reports.",
            "type":"string",
            "pattern": "^(\\.[/\\\\]|(\\.\\.[/\\\\])+|[a-zA-Z]:[/\\\\])?([a-zA-Z0-9_ \\-\\.\\*\\?\\[\\]]+[/\\\\])*[a-zA-Z0-9_ \\-\\.\\*\\?\\[\\]]+(xls|xlsx)$"
        },
        "template_path":{
            "title":"Template path",
            "description": "Path to a older containing templates in Jinja2 syntax to use in constructing the HTML Annual Performance Reports.",
            "type":"string",
            "pattern": "^(\\.[/\\\\]/|(\\.\\.[/\\\\])+|[a-zA-Z]:[/\\\\])?([a-zA-Z0-9_ \\-\\.]+[/\\\\])+$"
        },
        "template_name": {
            "title": "Template name",
            "description": "Name of the specific template to use for generating APRs.",
            "type": "string",
            "pattern": "^[a-zA-Z0-9_ \\-\\.]+(htm|html)"
        },
        "output_path":{
            "title":"Output path",
            "description": "Path to a folder to use for storing the HTML Annual Performance Reports.",
            "type":"string",
            "pattern": "^(\\.[/\\\\]/|(\\.\\.[/\\\\])+|[a-zA-Z]:[/\\\\])?([a-zA-Z0-9_ \\-\\.]+[/\\\\])+$"
        },
        "primary_grantee_worksheet_name": {
            "title": "Primary grantee worksheet name",
            "description": "The name of the worksheet containing the data values relevant to the prime grantees.",
            "type": "string"
        },
        "primary_grantee_key_worksheet_column": {
            "title": "Primary grantee key worksheet column",
            "description": "The column within the primary grantee worksheet containing the key value identifying the grantee, to use in correlating subawards from other worksheets.",
            "type": "integer"
        },
        "primary_grantee_key_name": {
            "title": "Primary grantee key name",
            "description": "The name assigned to the key value in the column listed above.",
            "type": "string"
        },
        "primary_grantee_keys": {
            "title": "Primary grantee keys",
            "description": "if present, this specifies a list of key values for which to generate output. If not present, output is produced for all primary grantees in the datafile.",
            "type": "array",
            "items" : {
                "type": "string",
                "minItems": 1,
                "uniqueItems": true
            }
        },
        "omb_control_number": {
            "title": "OMB control number",
            "description": "The identifier assigned to the approved Information Collection Instrument.",
            "type": "string"
        },
        "expiration_date": {
            "title": "Expiration date",
            "description": "The official date when approval to use the Information Collection Instrument ends.",
            "type": "string"
        },
        "cui_official": {
            "title": "CUI Official",
            "description": "The name of the official charged with maintaining the Controlled Unclassified Information in the Annual Performance Report.",
            "type": "string"
        },
        "filename_components": {
            "title": "Filename components",
            "description": "An array of data value names, from the field map, to use in generating a name for the HTML file. The subfund and reporting_year values are always used in the HTML file name. The additional components listed here help distinguish between the generated files and typically include at least the primary grantee key name.",
            "type": "array",
            "items": {
                "type": "string",
                "minItems": 1
            }
        },
        "main": {
            "title": "Main field map",
            "description": "The map of field locations for data values in the primary grantee worksheet.",
            "type": "array",
            "items": {
                "$ref": "/schemas/fieldMap.schema.json",
                "minItems": 1,
                "uniqueItems": true
            }
        },
        "subs": {
            "title": "",
            "description": "",
            "type": "array",
            "items": {
                "$ref": "/schemas/subawardsMap.schema.json"
            },
            "minItems": 0,
            "uniqueItems": true
        }
    },
    "required": [
        "subfund",
        "reporting_year",
        "datafile_pattern",
        "template_path",
        "template_name",
        "primary_grantee_worksheet_name",
        "primary_grantee_key_worksheet_column",
        "primary_grantee_key_name",
        "omb_control_number",
        "expiration_date",
        "cui_official",
        "filename_components",
        "main"
    ],
    "$defs": {
        "/schemas/fieldMap.schema.json": {
            "$schema":"https://json-schema.org/draft/2020-12/schema",
            "$id":"https://data.ed.gov/schemas/fieldMap.schema.json",
            "title":"Annual Performance Report Field Map",
            "description":"Specifies parameters for a data value location within a worksheet, and the type of data contained there.",
            "type": "object",
            "properties": {
                "name": {
                    "title": "Name",
                    "description": "The name of the field. The name is used in a template to identify where to write a data value in the generated HTML file.",
                    "type": "string"
                },
                "index": {
                    "title": "Index",
                    "description": "The column index (starting at 1) within the worksheet where the data value is located.",
                    "type": "integer"
                },
                "type": {
                    "title": "Type",
                    "description": "The type of data stored in the field.",
                    "enum": [
                        "bool",
                        "float",
                        "int",
                        "str"
                    ]
                }
            },
            "required": ["name","index","type"]
        },
        "/schemas/subawardsMap.schema.json": {
            "$schema":"https://json-schema.org/draft/2020-12/schema",
            "$id":"https://data.ed.gov/schemas/subawardsMap.schema.json",
            "title":"Annual Performance Report Subawards Map",
            "description":"Specifies parameters for extracting data values from potentially multiple workbooks of consolidated Annual Performance Report subaward responses.",
            "type": "object",
            "properties": {
                "name": {
                    "title": "Name",
                    "description": "The name to use for the list of subawards. This name is used in the template to identify where to write subaward data values from this list.",
                    "type": "string"
                },
                "children": {
                    "title": "Children",
                    "description": "A list of worksheet mappings to combine into the named list of subawards. This allows combining data values from multiple worksheets into a single subaward list for use in the template.",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "worksheet_name": {
                                "title": "Worksheet name",
                                "description": "The names of the worksheet containing the child subaward data values.",
                                "type": "string"
                            },
                            "key_offset": {
                                "title": "Key offset",
                                "description": "The column offset in which the primary grantee key value is stored. This column is expected to contain the same value as one of the primary grantees, to distinguish which subawards correspond to a given primary grantee.",
                                "type": "integer"
                            },
                            "field_map": {
                                "title": "Field map",
                                "description": "A list of field mappings for the subaward worksheet.",
                                "type": "array",
                                "items": {
                                    "$ref": "/schemas/fieldMap.schema.json",
                                    "minItems": 1,
                                    "uniqueItems": true
                                }
                            }
                        },
                        "required": ["worksheet_name","key_offset","field_map"]
                    }
                }
            },
            "required": ["name","children"]
        }
    }
}

=== katucker/esfapr/heer-2022-config.json
{
    "subfund": "HEER",
    "reporting_year": "2022",
    "datafile_pattern": "data/heer-2022-reopen-raw*.xlsx",
    "template_path": "templates/",
    "template_name": "heer_year3_apr.html",
    "output_path": "aprs/heer/2022/",
    "primary_grantee_worksheet_name": "prime",
    "primary_grantee_key_worksheet_column": 4,
    "primary_grantee_key_name": "uei",
    "omb_control_number": "1840-0850",
    "expiration_date": "1/31/2025",
    "cui_official": "Office of Postsecondary Education",
    "main": [
        {"name": "asOfDate", "index": 0, "type": "str"},
        {"name": "pk", "index": 1, "type": "str"},
        {"name": "sk", "index": 2, "type": "str"},
        {"name": "uei", "index": 3, "type": "str"},
        {"name": "dunsNumber", "index": 4, "type": "str"},
        {"name": "reportingYear", "index": 5, "type": "str"},
        {"name": "lastModifiedDate", "index": 6, "type": "str"},
        {"name": "lastModifiedBy", "index": 7, "type": "str"},
        {"name": "submittedDate", "index": 8, "type": "str"},
        {"name": "submittedBy", "index": 9, "type": "str"},
        {"name": "iheName", "index": 10, "type": "str"},
        {"name": "opeIds", "index": 11, "type": "str"},
        {"name": "unitIds", "index": 12, "type": "str"},
        {"name": "awards", "index": 13, "type": "str"},
        {"name": "awardedAmountsStudentAid", "index": 14, "type": "float"},
        {"name": "awardedAmountsInstitutional", "index": 15, "type": "float"},
        {"name": "awardedAmountsHbcu", "index": 16, "type": "float"},
        {"name": "awardedAmountsTccu", "index": 17, "type": "float"},
        {"name": "awardedAmountsMsi", "index": 18, "type": "float"},
        {"name": "awardedAmountsSip", "index": 19, "type": "float"},
        {"name": "awardedAmountsFipse", "index": 20, "type": "float"},
        {"name": "awardedAmountsProprietary", "index": 21, "type": "float"},
        {"name": "awardedAmountsSaihe", "index": 22, "type": "float"},
        {"name": "awardedAmountsSsarp", "index": 23, "type": "float"},
        {"name": "areHeerfAllFundsExpendedByEndReportingPeriod",
            "index": 24, "type": "bool"},
        {"name": "receivedTemporaryApproval", "index": 25, "type": "bool"},
        {"name": "receivedPermanentApproval", "index": 26, "type": "bool"},
        {"name": "primaryAccreditor", "index": 27, "type": "str"},
        {"name": "isAccreditedByAgency", "index": 28, "type": "bool"},
        {"name": "anyAidDeterminationStudentsAskedToApply",
            "index": 29, "type": "bool"},
        {"name": "anyAidDeterminationEmergencyFinancialAid",
            "index": 30, "type": "bool"},
        {"name": "anyAidDeterminationFoodPriority", "index": 31, "type": "bool"},
        {"name": "anyAidDeterminationHousingPriority",
            "index": 32, "type": "bool"},
        {"name": "anyAidDeterminationCourseMaterialPriority",
            "index": 33, "type": "bool"},
        {"name": "anyAidDeterminationTechnologyPriority",
            "index": 34, "type": "bool"},
        {"name": "anyAidDeterminationHealthCarePriority",
            "index": 35, "type": "bool"},
        {"name": "anyAidDeterminationChildCarePriority",
            "index": 36, "type": "bool"},
        {"name": "anyAidDeterminationTransportationPriority",
            "index": 37, "type": "bool"},
        {"name": "anyAidDeterminationLostIncomePriority",
            "index": 38, "type": "bool"},
        {"name": "anyAidDeterminationOtherPriority",
            "index": 39, "type": "bool"},
        {"name": "anyAidDeterminationOtherPriorityDescription",
            "index": 40, "type": "bool"},
        {"name": "anyAidDeterminationSupportingDocumentation",
            "index": 41, "type": "bool"},
        {"name": "anyAidDeterminationAdministrativeData",
            "index": 42, "type": "bool"},
        {"name": "anyAidDeterminationEnrollmentIntensityFactor",
            "index": 43, "type": "bool"},
        {"name": "anyAidDeterminationLocationFactor",
            "index": 44, "type": "bool"},
        {"name": "anyAidDeterminationPellGrantFactor",
            "index": 45, "type": "bool"},
        {"name": "anyAidDeterminationFafsaDataElementsFactor",
            "index": 46, "type": "bool"},
        {"name": "anyAidDeterminationFafsaFamilyIncomeFactor",
            "index": 47, "type": "bool"},
        {"name": "anyAidDeterminationEstimatedFamilyContributionFactor",
            "index": 48, "type": "bool"},
        {"name": "anyAidDeterminationIndependentDependentStatusFactor",
            "index": 49, "type": "bool"},
        {"name": "anyAidDeterminationOnOffCampusEducationStatusFactor",
            "index": 50, "type": "bool"},
        {"name": "anyAidDeterminationOnOffCampusLivingArrangementsFactor",
            "index": 51, "type": "bool"},
        {"name": "anyAidDeterminationAcademicLevelFactor",
            "index": 52, "type": "bool"},
        {"name": "anyAidDeterminationOtherFactor", "index": 53, "type": "bool"},
        {"name": "anyAidDeterminationOtherFactorDescription",
            "index": 54, "type": "bool"},
        {"name": "anyAidDeterminationSpecificMethodology",
            "index": 55, "type": "bool"},
        {"name": "aidDeterminationMethodologyFiles", "index": 56, "type": "str"},
        {"name": "anyDistributedByCheck", "index": 57, "type": "bool"},
        {"name": "anyDistributedByEtfDirectDeposit",
            "index": 58, "type": "bool"},
        {"name": "anyDistributedByDebitCard", "index": 59, "type": "bool"},
        {"name": "anyDistributedByPaymentApp", "index": 60, "type": "bool"},
        {"name": "anyDistributedByOther", "index": 61, "type": "bool"},
        {"name": "distributedByOtherDescription", "index": 62, "type": "str"},
        {"name": "enabledContinuePlannedPrograms", "index": 63, "type": "int"},
        {"name": "enabledStudentsPricesToPrePandemic",
            "index": 64, "type": "int"},
        {"name": "enabledStudentsDevicesAndInternet", "index": 65, "type": "int"},
        {"name": "enabledStudentsDirectFinancialSupport",
            "index": 66, "type": "int"},
        {"name": "enabledStaffKeepFullSalaryPandemic",
            "index": 67, "type": "int"},
        {"name": "enabledAllPurchaseCovidTests", "index": 68, "type": "int"},
        {"name": "anyEmergencyFinancialAidInstructions",
            "index": 69, "type": "bool"},
        {"name": "emergencyFinancialAidInstructionsFiles",
            "index": 70, "type": "str"},
        {"name": "nEnrolledStudentsNotEligibleTitleIV",
            "index": 71, "type": "int"},
        {"name": "pEnrolledStudentsNotEligibleTitleIV",
            "index": 72, "type": "float"},
        {"name": "nStudentsReceivedGrantsNotEligibleTitleIV",
            "index": 73, "type": "int"},
        {"name": "pStudentsGrantedHeerNotEligibleTitleIV",
            "index": 74, "type": "float"},
        {"name": "aiEnrolledStudentCount", "index": 75, "type": "int"},
        {"name": "aiReceivedAidGrant", "index": 76, "type": "int"},
        {"name": "aiTotalAmountOfGrants", "index": 77, "type": "float"},
        {"name": "aiAverageHeerfAward", "index": 78, "type": "float"},
        {"name": "aEnrolledStudentCount", "index": 79, "type": "int"},
        {"name": "aReceivedAidGrant", "index": 80, "type": "int"},
        {"name": "aTotalAmountOfGrants", "index": 81, "type": "float"},
        {"name": "aAverageHeerfAward", "index": 82, "type": "float"},
        {"name": "bEnrolledStudentCount", "index": 83, "type": "int"},
        {"name": "bReceivedAidGrant", "index": 84, "type": "int"},
        {"name": "bTotalAmountOfGrants", "index": 85, "type": "float"},
        {"name": "bAverageHeerfAward", "index": 86, "type": "float"},
        {"name": "hEnrolledStudentCount", "index": 87, "type": "int"},
        {"name": "hReceivedAidGrant", "index": 88, "type": "int"},
        {"name": "hTotalAmountOfGrants", "index": 89, "type": "float"},
        {"name": "hAverageHeerfAward", "index": 90, "type": "float"},
        {"name": "nhEnrolledStudentCount", "index": 91, "type": "int"},
        {"name": "nhReceivedAidGrant", "index": 92, "type": "int"},
        {"name": "nhTotalAmountOfGrants", "index": 93, "type": "float"},
        {"name": "nhAverageHeerfAward", "index": 94, "type": "float"},
        {"name": "wEnrolledStudentCount", "index": 95, "type": "int"},
        {"name": "wReceivedAidGrant", "index": 96, "type": "int"},
        {"name": "wTotalAmountOfGrants", "index": 97, "type": "float"},
        {"name": "wAverageHeerfAward", "index": 98, "type": "float"},
        {"name": "tmrEnrolledStudentCount", "index": 99, "type": "int"},
        {"name": "tmrReceivedAidGrant", "index": 100, "type": "int"},
        {"name": "tmrTotalAmountOfGrants", "index": 101, "type": "float"},
        {"name": "tmrAverageHeerfAward", "index": 102, "type": "float"},
        {"name": "urEnrolledStudentCount", "index": 103, "type": "int"},
        {"name": "urReceivedAidGrant", "index": 104, "type": "int"},
        {"name": "urTotalAmountOfGrants", "index": 105, "type": "float"},
        {"name": "urAverageHeerfAward", "index": 106, "type": "float"},
        {"name": "nrEnrolledStudentCount", "index": 107, "type": "int"},
        {"name": "nrReceivedAidGrant", "index": 108, "type": "int"},
        {"name": "nrTotalAmountOfGrants", "index": 109, "type": "float"},
        {"name": "nrAverageHeerfAward", "index": 110, "type": "float"},
        {"name": "ncrEnrolledStudentCount", "index": 111, "type": "int"},
        {"name": "ncrReceivedAidGrant", "index": 112, "type": "int"},
        {"name": "ncrTotalAmountOfGrants", "index": 113, "type": "float"},
        {"name": "ncrAverageHeerfAward", "index": 114, "type": "float"},
        {"name": "mEnrolledStudentCount", "index": 115, "type": "int"},
        {"name": "mReceivedAidGrant", "index": 116, "type": "int"},
        {"name": "mTotalAmountOfGrants", "index": 117, "type": "float"},
